### PR TITLE
Draw

### PR DESCRIPTION
**Pull request by VanshikaSabharwal**
This is a sub issue #35  of issue #29

I have added husky and pre-commits.

@dhruvpatidar359 you can merge husky for a consistent code workflow.

### CODE REVIEW

**Comment by VanshikaSabharwal** [comment]
hey @dhruvpatidar359 , Can you please merge my PR.

**Comment by dhruvpatidar359** [comment]
Actually there is some issue in the eslintsec.config file , which is
causing the eslint check to not work in production . I have tried to
resolve it , but failed will share that soon

**Comment by VanshikaSabharwal** [comment]
Okay . Do tell me if any help needed @dhruvpatidar359 . I'll do my best

**Comment by dhruvpatidar359** [comment]
> Okay . Do tell me if any help needed @dhruvpatidar359 . I'll do my best

Have a look 👀
image

**Comment by dhruvpatidar359** [comment]
> > Okay . Do tell me if any help needed @dhruvpatidar359 . I'll do my best
> 
> Have a look 👀 image

This was the original error 
image

**Comment by dhruvpatidar359** [comment]
the deployment works well , but i think the eslint rules are breaking in this

**Comment by VanshikaSabharwal** [comment]
> the deployment works well , but i think the eslint rules are breaking in this

Yes, Have you tried downloading @typescript-eslint/eslint-plugin?

**Comment by dhruvpatidar359** [comment]
may you please update the `npm i @typescript-eslint/parser` and add the package that u said . In the PR

**Comment by VanshikaSabharwal** [comment]
> may you please update the `npm i @typescript-eslint/parser` and add the package that u said . In the PR

Okay, I am doing it

**Comment by VanshikaSabharwal** [comment]
I have installed @typescript-eslint/parser and @typescript-eslint/eslint-plugin. Good to go @dhruvpatidar359

**Comment by dhruvpatidar359** [comment]
image

i think still there is some issue with this .

**Comment by VanshikaSabharwal** [comment]
> image
> 
> i think still there is some issue with this .

Hmm, I think this issue is due to 

> image
> 
> i think still there is some issue with this .

Prop type is not defined that is why the build failed. 

The errors are indication that eslint is working fine and wants us to resolve every error in code.

**Comment by dhruvpatidar359** [comment]
@VanshikaSabharwal  right now , i have merged your commits , directly into the master . So i can't merge this PR any more . What we can do is create a new PR again represeting the same issue . But with other code change if you can , but we can't add this code anymore . I will tag that PR as gssoc and level3 . 

Actully i had to do that because , Props Type issue is not coming in the master , so i just cherry picked you commits and put those in the master . So don't worry , open a new PR i will merge it directly for you . 👩‍🚀

**Pull request closed without merging**
