### PR TITLE
added panning option using mouse click and space key

### PR DESCRIPTION
**Pull request by a-khushal**
solution to issue: #7 
Here is a screen recording of the working functionality:

[Screencast from 13-05-24 12:55:34 AM IST.webm](https://github.com/dhruvpatidar359/nextdraw/assets/132923704/bb1184e1-4122-48ee-8bbc-ebb81624f87a)

### CODE REVIEW

**Comment by dhruvpatidar359** [comment]
LGTM ♥ Merging

**Comment by a-khushal** [comment]
> LGTM ♥ merging

🔥🫂

**Comment by dhruvpatidar359** [comment]
There is some code break in the main production line due to this PR, can you please check this why it is happening so . When i press the delete button ,it does not works instantly ,i have to press it twice . The same goes with the tools section also . 

May you please confirm and check this out 👩‍🚀

**Comment by a-khushal** [comment]
Working on it

**Comment by a-khushal** [comment]
I have raised a PR https://github.com/dhruvpatidar359/nextdraw/pull/46

**Pull request merged**
