### PR TITLE
Fill style option implemented for elements

### PR DESCRIPTION
**Pull request by atharvarekhawar**
This PR solves issue #10 Add fillStyle options in the shapes

### CODE REVIEW

**Review by dhruvpatidar359 — CHANGES_REQUESTED** [review]
I think there is some issues in the code :
1 ) When i select a particular style i think it is rerendering its position inside the style which causing the shape to glitch .
2 ) After applying a style , if i see the property tab it is default to solid .

Have a look 

https://github.com/dhruvpatidar359/nextdraw/assets/103873587/9db6e65c-65f5-4a6d-b7e7-8dc82e6cd44a

**Comment by atharvarekhawar** [comment]
@dhruvpatidar359 I have solved the second issue, where the fill style was always updating to solid but in the first issue I think that is how the rough.js implementation is for adding fillStyle, and there is no more information about fillStyle in their documentation.

should I commit new changes?

**Comment by dhruvpatidar359** [comment]
> @dhruvpatidar359 I have solved the second issue, where the fill style was always updating to solid but in the first issue I think that is how the rough.js implementation is for adding fillStyle, and there is no more information about fillStyle in their documentation.
> 
> should I commit new changes?

you are correct it is in their implementation actually . In such case we should remove the dotted one . Comment down the code for that one , will look into it in future . 

LGTM , you can commit now 👩‍🚀 .

**Review by dhruvpatidar359 — APPROVED** [review]

**Comment by atharvarekhawar** [comment]
done with the changes and pushed the code, you can merge it now @dhruvpatidar359

**Review by dhruvpatidar359 — CHANGES_REQUESTED** [review]
One thing is still buggy have a look : i selected some other option but it defaults to the solid one .

https://github.com/dhruvpatidar359/nextdraw/assets/103873587/76920470-29bb-46de-8d13-25baa6c0e8d7

**Comment by atharvarekhawar** [comment]
@dhruvpatidar359 done with the changes , you can review it.

**Comment by dhruvpatidar359** [comment]
LGTM , A huge applause to you buddy 👏  .

**Review by dhruvpatidar359 — APPROVED** [review]

**Pull request merged**
