### PR TITLE
Created close-old-issue.yml

### LINKED ISSUE #49: Workflow for Closing Old Issues
**Please describe your feature.**
This feature aims to automate the process of managing old issues, ensuring that the repository remains organized and focused on relevant tasks. By automatically closing old issues, it reduces manual overhead for repository maintainers and helps keep the issue tracker tidy and up-to-date.

**Describe the solution you'd like**
I would like a workflow that automatically identifies and closes old issues based on certain criteria, such as no recent activity or being open for a specific duration.

### PR DESCRIPTION
**Pull request by Asymtode712**
Fixes #49

### CODE REVIEW

**Comment by Asymtode712** [comment]
@dhruvpatidar359 please review my PR and merge it if it is good to go

**Comment by dhruvpatidar359** [comment]
@Asymtode712  Hi , make sure that the PR does not include the Contributing.md of some other git repository . 
Please modify it correctly and to the point .

**Review by dhruvpatidar359 — CHANGES_REQUESTED** [review]
change the git that is mentioned in the body part of this file

**Comment by Asymtode712** [comment]
@dhruvpatidar359 I have done the changes as requested by you, please review my PR and merge it with relevent gssoc labels if it is good to go

**Comment by Asymtode712** [comment]
@dhruvpatidar359 I have done the changes as requested by you, please review my PR and merge it with relevent gssoc labels if it is good to go

**Pull request closed without merging**
