### PR TITLE
add: eraser feature

### LINKED ISSUE #2: Eraser is missing
- [✅ ] Tried NextDraw ?

What is Currently present in the nextdraw :
1 ) Only delete button works for deleting the selected element.

### Features:

There is no Eraser present in Nextdraw yet. 

image

Guide : 
Eraser can be created by just detecing if there are elements present below the mouse pointer or not . If they are there , we can delete the  elements , which are detected by the mouse . 
1 ) We can use getElementBelow() function  to get the below element which is present in Element.js file.
2 ) Now you can remove the element .

### PR DESCRIPTION
**Pull request by Shobhit-Nagpal**
fixes : #2

Changes:
- added eraser icon in top bar
- added eraser icon in circular toolbar
- added an eraseElement function in Element.js file
- added an if condition checking for eraser tool in handleMouseDown in Canvas.jsx
- added condition to not show properties menu when eraser is selected
- handles erasing elements for rooms with help of web sockets event emitter

Working (recording):
[eraser-feature.webm](https://github.com/dhruvpatidar359/nextdraw/assets/74096450/0a91aef0-071f-400d-a580-9e705e0a6851)

### CODE REVIEW

**Review by dhruvpatidar359 — CHANGES_REQUESTED** [review]
Hi @Shobhit-Nagpal  thanks for the contribution . It really matters , but i think your code has breaked some functioanlity to assign properties to already present shapes .

- > May you please ensure that the property assignement to already ensured shapes works again.
- Have a look

https://github.com/dhruvpatidar359/nextdraw/assets/103873587/c87ee53d-d492-4a82-9f54-97e946481886



- > One more thing to consider is that , there is a ShapeCache and undo/redo functionality . You have to take care of these two also .



The ShapeCache is a kind of a weakmap (consider it has a hashmap in java but having some different characterstics ) , it is used to keep the shapes in cache , so whenever a new rendering is done the shapes are used from this place only , they are not rebuild or reexecuted . It is like we using a already stored value.

- > One more thing we can consider in this , is chaning the mouse coursor icon to some thing erasery .

**Comment by Shobhit-Nagpal** [comment]
my bad. i'll fix this up

**Comment by Shobhit-Nagpal** [comment]
hey @dhruvpatidar359, fixed the issue. turns out i placed a wrong condition in the if check for rendering properties in the PropertiesTab component.

Made the following changes:
- cursor changes to eraser icon when eraser is selected
- changed position of eraser to be beside text in the circular menu
- fixed the functionality to add style after an shape is rendered.
- kept the redo and undo feature in mind and they seem to be working fine.

Working below:

[eraser-fix.webm](https://github.com/dhruvpatidar359/nextdraw/assets/74096450/f34d03e8-1af5-4437-91fc-a8433d57a621)

**Review by dhruvpatidar359 — APPROVED** [review]

**Comment by dhruvpatidar359** [comment]
LGTM , Merging

**Pull request merged**
